### ISSUE TITLE
No module named 'config'

### ISSUE THREAD

**Issue by Endogen** [KELs7/flake8-contracting#1]
I have a folder with contracts and I want to check them with flake8 and your ruleset. First I created a venv in that folder. Then I installed `flake8` and then installed your ruleset. But if I run `flake8` then i get the following error:

```
Traceback (most recent call last):
  File "/Users/endogen/anaconda3/lib/python3.11/site-packages/flake8/plugins/finder.py", line 291, in _load_plugin
    obj = plugin.entry_point.load()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/endogen/anaconda3/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/endogen/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/endogen/Projekte/xian-flake8-contracting/flake8_contracting.py", line 3, in <module>
    from contractingLinter.linter import Linter
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/endogen/Projekte/xian-flake8-contracting/contractingLinter/linter.py", line 4, in <module>
    import config
ModuleNotFoundError: No module named 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/endogen/anaconda3/bin/flake8", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/endogen/anaconda3/lib/python3.11/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/Users/endogen/anaconda3/lib/python3.11/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/Users/endogen/anaconda3/lib/python3.11/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/Users/endogen/anaconda3/lib/python3.11/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
                                 ^^^^^^^^^^^^^^^^
  File "/Users/endogen/anaconda3/lib/python3.11/site-packages/flake8/options/parse_args.py", line 42, in parse_args
    plugins = finder.load_plugins(raw_plugins, plugin_opts)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/endogen/anaconda3/lib/python3.11/site-packages/flake8/plugins/finder.py", line 365, in load_plugins
    return _classify_plugins(_import_plugins(plugins, opts), opts)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/endogen/anaconda3/lib/python3.11/site-packages/flake8/plugins/finder.py", line 307, in _import_plugins
    return [_load_plugin(p) for p in plugins]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/endogen/anaconda3/lib/python3.11/site-packages/flake8/plugins/finder.py", line 307, in <listcomp>
    return [_load_plugin(p) for p in plugins]
            ^^^^^^^^^^^^^^^
  File "/Users/endogen/anaconda3/lib/python3.11/site-packages/flake8/plugins/finder.py", line 293, in _load_plugin
    raise FailedToLoadPlugin(plugin.package, e)
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "flake8-contracting" due to No module named 'config'.
```

I also tried to install that module with `pip install config` but same error

**Comment by KELs7** [comment]
Which python version are you using? And what version of flake8 was installed?

**Comment by KELs7** [comment]
`config` is a file in the `contractingLinter folder`
![Screenshot_20240411-014750](https://github.com/KELs7/flake8-contracting/assets/52892093/2245fe19-6100-4d90-bb82-11f3c6cab07c)

**Comment by KELs7** [comment]
Probably a path issue. Add the absolute path of `flake8-contracting` 👉`/Users/endogen/Projekte/xian-flake8-contracting` to your PYTHONPATH environment variable. Hope this fixes it.

**Comment by KELs7** [comment]
`config` is a file in the `contractingLinter folder` which is imported by `linter.py`.
![Screenshot_20240411-014750](https://github.com/KELs7/flake8-contracting/assets/52892093/2245fe19-6100-4d90-bb82-11f3c6cab07c)

**Comment by KELs7** [comment]
I am going to automatically add the absolute path of the package to PYTHONPATH when installing

**Comment by KELs7** [comment]
I have identified the real issue and pushed a commit that resolves it https://github.com/KELs7/flake8-contracting/commit/cbb259365f02235b760a361baf0ff5009c83c7b7

Edit: fixed an undefined bug due to the previous commit when linting contract code https://github.com/KELs7/flake8-contracting/commit/1dd9e2ae3f3451bdb66c7154dee476fb37e03975

**Comment by Endogen** [comment]
That worked, thanks!
